import type { ProductionEntry } from './types';

export const shifts = ['1st', '2nd', '3rd', 'Weekend'] as const;
export const machines = ['Pipe Line 1', 'Pipe Line 2', 'Pipe Line 3', 'Spiral Line', 'Finishing Cell'];
export const operators = ['Steve', 'Alicia', 'Marcus', 'Priya', 'Jordan', 'Dana'];
export const downtimeReasons = [
  'None',
  'Sensor Fault',
  'Material Delay',
  'Changeover',
  'Maintenance',
  'Quality Check',
  'Staffing',
];

export const emptyEntry: ProductionEntry = {
  id: '',
  date: '2026-05-25',
  shift: '1st',
  machine: 'Pipe Line 1',
  operatorName: 'Steve',
  shiftHours: 8.5,
  breakMinutes: 60,
  setupCount: 3,
  standardSetupMinutes: 20,
  actualSetupMinutes: 22,
  downtimeMinutes: 20,
  cycleTimeSeconds: 32,
  actualPipeQuantity: 600,
  scrapQuantity: 8,
  downtimeReason: 'None',
  notes: '',
};

export const sampleEntries: ProductionEntry[] = [
  {
    id: 'sample-2026-05-22-1',
    date: '2026-05-22',
    shift: '1st',
    shiftHours: 8.5,
    breakMinutes: 60,
    setupCount: 4,
    standardSetupMinutes: 20,
    actualSetupMinutes: 26,
    downtimeMinutes: 28,
    cycleTimeSeconds: 32,
    actualPipeQuantity: 596,
    scrapQuantity: 12,
    downtimeReason: 'Sensor Fault',
    operatorName: 'Steve',
    machine: 'Pipe Line 1',
    notes: 'Required demo validation row.',
  },
  {
    id: 'sample-2026-05-18-1',
    date: '2026-05-18',
    shift: '1st',
    machine: 'Pipe Line 2',
    operatorName: 'Alicia',
    shiftHours: 8,
    breakMinutes: 45,
    setupCount: 3,
    standardSetupMinutes: 18,
    actualSetupMinutes: 19,
    downtimeMinutes: 15,
    cycleTimeSeconds: 30,
    actualPipeQuantity: 660,
    scrapQuantity: 7,
    downtimeReason: 'None',
    notes: 'Steady morning run.',
  },
  {
    id: 'sample-2026-05-18-2',
    date: '2026-05-18',
    shift: '2nd',
    machine: 'Pipe Line 1',
    operatorName: 'Marcus',
    shiftHours: 8,
    breakMinutes: 45,
    setupCount: 5,
    standardSetupMinutes: 20,
    actualSetupMinutes: 28,
    downtimeMinutes: 44,
    cycleTimeSeconds: 34,
    actualPipeQuantity: 485,
    scrapQuantity: 16,
    downtimeReason: 'Changeover',
    notes: 'Longer actual setups.',
  },
  {
    id: 'sample-2026-05-19-1',
    date: '2026-05-19',
    shift: '1st',
    machine: 'Spiral Line',
    operatorName: 'Priya',
    shiftHours: 8.5,
    breakMinutes: 60,
    setupCount: 2,
    standardSetupMinutes: 25,
    actualSetupMinutes: 24,
    downtimeMinutes: 8,
    cycleTimeSeconds: 38,
    actualPipeQuantity: 610,
    scrapQuantity: 4,
    downtimeReason: 'None',
    notes: 'Setup beat standard.',
  },
  {
    id: 'sample-2026-05-19-2',
    date: '2026-05-19',
    shift: '3rd',
    machine: 'Pipe Line 3',
    operatorName: 'Jordan',
    shiftHours: 8,
    breakMinutes: 45,
    setupCount: 1,
    standardSetupMinutes: 20,
    actualSetupMinutes: 20,
    downtimeMinutes: 70,
    cycleTimeSeconds: 29,
    actualPipeQuantity: 512,
    scrapQuantity: 9,
    downtimeReason: 'Material Delay',
    notes: 'Late material staging.',
  },
  {
    id: 'sample-2026-05-20-1',
    date: '2026-05-20',
    shift: '1st',
    machine: 'Finishing Cell',
    operatorName: 'Dana',
    shiftHours: 7.5,
    breakMinutes: 30,
    setupCount: 0,
    standardSetupMinutes: 20,
    actualSetupMinutes: 0,
    downtimeMinutes: 18,
    cycleTimeSeconds: 45,
    actualPipeQuantity: 498,
    scrapQuantity: 5,
    downtimeReason: 'Quality Check',
    notes: 'No setup count; setup efficiency shown as 100%.',
  },
  {
    id: 'sample-2026-05-20-2',
    date: '2026-05-20',
    shift: '2nd',
    machine: 'Pipe Line 2',
    operatorName: 'Steve',
    shiftHours: 8.5,
    breakMinutes: 60,
    setupCount: 4,
    standardSetupMinutes: 18,
    actualSetupMinutes: 23,
    downtimeMinutes: 25,
    cycleTimeSeconds: 31,
    actualPipeQuantity: 620,
    scrapQuantity: 11,
    downtimeReason: 'Maintenance',
    notes: 'Short maintenance stop.',
  },
  {
    id: 'sample-2026-05-21-1',
    date: '2026-05-21',
    shift: '1st',
    machine: 'Pipe Line 1',
    operatorName: 'Alicia',
    shiftHours: 8.5,
    breakMinutes: 60,
    setupCount: 3,
    standardSetupMinutes: 20,
    actualSetupMinutes: 20,
    downtimeMinutes: 12,
    cycleTimeSeconds: 32,
    actualPipeQuantity: 670,
    scrapQuantity: 6,
    downtimeReason: 'None',
    notes: 'Good availability.',
  },
  {
    id: 'sample-2026-05-21-2',
    date: '2026-05-21',
    shift: '2nd',
    machine: 'Spiral Line',
    operatorName: 'Marcus',
    shiftHours: 8,
    breakMinutes: 45,
    setupCount: 4,
    standardSetupMinutes: 25,
    actualSetupMinutes: 31,
    downtimeMinutes: 36,
    cycleTimeSeconds: 39,
    actualPipeQuantity: 496,
    scrapQuantity: 15,
    downtimeReason: 'Sensor Fault',
    notes: 'Sensor adjustment before break.',
  },
  {
    id: 'sample-2026-05-23-1',
    date: '2026-05-23',
    shift: 'Weekend',
    machine: 'Pipe Line 3',
    operatorName: 'Priya',
    shiftHours: 6,
    breakMinutes: 30,
    setupCount: 2,
    standardSetupMinutes: 20,
    actualSetupMinutes: 18,
    downtimeMinutes: 10,
    cycleTimeSeconds: 30,
    actualPipeQuantity: 565,
    scrapQuantity: 4,
    downtimeReason: 'None',
    notes: 'Short weekend run.',
  },
  {
    id: 'sample-2026-05-24-1',
    date: '2026-05-24',
    shift: 'Weekend',
    machine: 'Finishing Cell',
    operatorName: 'Jordan',
    shiftHours: 6,
    breakMinutes: 30,
    setupCount: 1,
    standardSetupMinutes: 20,
    actualSetupMinutes: 25,
    downtimeMinutes: 95,
    cycleTimeSeconds: 44,
    actualPipeQuantity: 300,
    scrapQuantity: 42,
    downtimeReason: 'Staffing',
    notes: 'Suspicious scrap level for demo highlighting.',
  },
];
